### ISSUE TITLE
REMO2020 wrong version_realization

### ISSUE THREAD

**Issue by jesusff** [euro-cordex/joint-evaluation#12]
REMO2020 data use _v1_ as `version_realization` instead of _v1-r1_

https://github.com/euro-cordex/joint-evaluation/blob/88bb24b41278bafc1d8d4b69e3155e1a19b4f4ce/catalog.csv?plain=1#L2C188-L2C190

**Comment by larsbuntemeyer** [comment]
Thanks @jesusff for pointing this out! You are right, this was still my old setting (I'll have to read the specs more carfully, i guess, urgg...) . I think, I should maybe also define a regex for it in the CV similar to the [driving_variant_label](https://github.com/WCRP-CORDEX/cordex-cmip6-cmor-tables/blob/430f1f5ae00af4c8931d1cc35917c8e912675cee/Tables/CORDEX-CMIP6_CV.json#L1676). I'll make that an issue in the [cv repo](https://github.com/WCRP-CORDEX/cordex-cmip6-cv).

**Comment by larsbuntemeyer** [comment]
See also https://github.com/WCRP-CORDEX/cordex-cmip6-cv/issues/233

**Comment by larsbuntemeyer** [comment]
Closed via https://github.com/euro-cordex/joint-evaluation/commit/620cd16223916dbf76989f2102deafe5e5568e90
